# I should create name for my blog, like "Stack Problems"
title: theel0ja's Site
description: Insert nice description
author: Elias Ojala
github: https://github.com/theel0ja
# about: Insert description about yourself
avatar_url: https://storage.theel0ja.info/theel0ja-assets/profile-pic.jpg?ref=theel0ja.info

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
  - icon: fa-twitter
    link: "https://twitter.com/theel0ja"
  - icon: fa-github
    link: "https://github.com/theel0ja"

share:
  twitter_username: theel0ja

urls:
  - text: About Me
    url: /about/
  - text: My Projects
    url: /projects/
  - text: XML Feed
    url: /feed.xml

url: "https://theel0ja.info"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
